name: 'Pull Request'

on: ['pull_request']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn test:unit:ci
      - run: yarn test:static
      - name: Danger
        run: yarn danger ci
        env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  styleguide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn styleguide:build
      - name: Uploading styleguide artifact
        uses: actions/upload-artifact@v2
        with:
          name: styleguide
          path: docs/
